language: cpp
os: linux
addons:
        apt:
          sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
          packages:
            - g++-10

compiler:
  - gcc

cache:
- directories:
  - $HOME/.cache

before_install:
  - sudo apt-get -y install libxml2-dev
  - sudo apt-get -y install lcov

script: ./testing

after_success:
- lcov --directory . --capture --output-file coverage.info
- lcov --remove coverage.info '/usr/*' './tests/catch/*' "${HOME}"'/.cache/*' --output-file coverage.info
- lcov --list coverage.info
- bash <(curl -s https://codecov.io/bash) -f coverage.info || echo "Codecov did not collect coverage reports"


notifications:
  email:
    - konrad_kraemer@yahoo.de
