language: cpp
os: linux
addons:
        apt:
          sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
          packages:
            - g++-9
            - lcov

compiler:
  - gcc-9

cache:
- directories:
  - $HOME/.cache

before_install:
  - sudo apt-get -y install lcov

script: ./testing

after_success:
- bash <(curl -s https://codecov.io/bash) -f coverage.info || echo "Codecov did not collect coverage reports"


notifications:
  email:
    - konrad_kraemer@yahoo.de
