language: cpp
os: linux

compiler:
  - clang
  - gcc

before_install:
  - sudo apt-get -y install libxml2-dev
  - sudo apt-get -y install lcov
  - sudo apt-get -y install libstdc++-7-dev

install:
- make get-deps
- mkdir -p $HOME/.cache
- touch $HOME/.cache/mydependency.so

script: ./testing

after_success:
- lcov --directory . --capture --output-file coverage.info
- lcov --remove coverage.info '/usr/*' './tests/catch/*' "${HOME}"'/.cache/*' --output-file coverage.info
- lcov --list coverage.info
- bash <(curl -s https://codecov.io/bash) -f coverage.info || echo "Codecov did not collect coverage reports"


notifications:
  email:
    - konrad_kraemer@yahoo.de
