anguage: cpp
os: linux
compiler: gcc

cache:
- directories:
  - $HOME/.cache

addons:
  apt:
    packages: 
    	- lcov
        - libstdc++-7-dev

install:
- mkdir -p $HOME/.cache
- touch $HOME/.cache/mydependency.so

script: ./testing

after_success:
- lcov --directory . --capture --output-file coverage.info
- lcov --remove coverage.info '/usr/*' './tests/catch/*' "${HOME}"'/.cache/*' --output-file coverage.info
- lcov --list coverage.info
- bash <(curl -s https://codecov.io/bash) -f coverage.info || echo "Codecov did not collect coverage reports"


notifications:
  email:
    - konrad_kraemer@yahoo.de
