#!/bin/bash
g++-9 --coverage ./tests/alltests.cpp -std=c++17 
./a.out
${TRAVIS_BUILD_DIR}/lcov-1.14/bin/lcov --gcov-tool /usr/bin/gcov-9.0 --version
lcov --directory . --capture --output-file coverage.info
lcov --remove coverage.info '/usr/*' './tests/catch/*' "${HOME}"'/.cache/*' --output-file coverage.info
lcov --list coverage.info

