#!/bin/bash
g++-8 --coverage ./tests/alltests.cpp -std=c++17
./a.out
lcov --directory . --capture --output-file coverage.info
lcov --remove coverage.info '/usr/*' './tests/catch/*' "${HOME}"'/.cache/*' --output-file coverage.info
lcov --list coverage.info

