name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: configure
      run: |
        cd ./tests/
        g++ BaseStore_Tests.cpp -std=c++20
    - name: Run tests
      run: |
        cd ./tests/
        ./a.out
