on: pull_request

name: Continuous Integration

jobs:
  coverage_report:
    name: Generate coverage report
    needs: testing
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    # ... Generate LCOV files or download it from a different job
    - name: Report code coverage
      uses: zgosalvez/github-actions-report-lcov@v1
      with:
        coverage-files: tests/coverage.info
        minimum-coverage: 75
        artifact-name: code-coverage-report
        github-token: ${{ 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 }}
        working-directory: apps/my-first-app
